### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by emmanuelol** [slayellow/CalibDNN_with_Pytorch#1]
Hi, thanks for sharing your work. I tried to train the model from scratch based on your repository, but the train's performance has been bad. Then I noticed that I'm not using pre-trained models for ResNet18 and DepthNet. Such models are needed pre-trained for the model to perform better. The models are the pre-trained ones provided by PyTorch (at least the ResNet18). Or how were such models trained?
Thanks in advance, bests.

**Comment by slayellow** [comment]
> Hi, thanks for sharing your work. I tried to train the model from scratch based on your repository, but the train's performance has been bad. Then I noticed that I'm not using pre-trained models for ResNet18 and DepthNet. Such models are needed pre-trained for the model to perform better. The models are the pre-trained ones provided by PyTorch (at least the ResNet18). Or how were such models trained?
> Thanks in advance, bests.

hi. I'll give you the ResNet18 model you want. 
Since ResNet18 and DepthNet have the same model type, you can use the same file, or just change the name to DepthNet.pth.

-> https://drive.google.com/drive/folders/1k_h5983nkn0Asz-o990TVn4ZY2ihF0cR?usp=sharing

And since this paper did not provide the code, I made it myself, but the results did not come out as well as this paper.

Thank you.

**Comment by emmanuelol** [comment]
Thanks!!

**Comment by eren-aydemir** [comment]
Hello @slayellow, thanks for your effort.

Drive link seems expired. Can you please re-share it?
